### ISSUE TITLE
Build failed due to deleted branch socfpga-4.1.33-ltsi .

### ISSUE THREAD

**Issue by gandautama** [01org/meta-de10-nano#12]
Build failed due to deleted branch socfpga-4.1.33-ltsi.
BUILD LOG:
WARNING: linux-altera-ltsi-4.1.33-ltsi+gitAUTOINC+b84195c056-r0 do_fetch: Failed to fetch URL git://github.com/altera-opensource/linux-socfpga.git;protocol=https;branch=socfpga-4.1.33-ltsi, attempting MIRRORS if available
DEBUG: linux-altera-ltsi-4.1.33-ltsi+gitAUTOINC+b84195c056-r0 do_fetch: Fetcher failure: Unable to find revision b84195c056ee943efa9eff2767b09dd266a451d1 in branch socfpga-4.1.33-ltsi even from upstream

As mentioned in [https://github.com/kraj/meta-altera/issues/78]

[https://github.com/altera-opensource/linux-socfpga]
does no longer contain a socfpga-4.1.33-ltsi branch.
Only socfpga-4.9.78-ltsi , tip is e681fba61a85fa13e546bba277083c49c091e361 .

**Comment by embeddman** [comment]
Hello! How to add new kernel 4.9.78 instead of 4.1.33 which is no available?

**Comment by dwesterg** [comment]
you should move to 4.14.73.  Which branch are you on?

**Comment by embeddman** [comment]
I'm on default branch 4.1.33, which doesn't work. How to move to 4.14.73 branch?

**Comment by dwesterg** [comment]
try https://github.com/feddischson/meta-de10-nano.  i have not as of yet updated the meta-de10-nano repo.

**Comment by gandautama** [comment]
Ok I will move to that fork.
