### ISSUE TITLE
Board can't load due to wrong partition ID

### ISSUE THREAD

**Issue by grebenkoff** [01org/meta-de10-nano#8]
bitbake produces image with wrong partition ID:
$ sudo losetup --show -f Angstrom-de10-nano-image-glibc-ipk-v2016.12-de10-nano.rootfs.socfpga-sdimg 
/dev/loop0
$ sudo fdisk /dev/loop0 
Command (m for help): p
...
Device       Boot  Start     End Sectors  Size Id Type
/dev/loop0p1 *      6144  210943  204800  100M  c W95 FAT32 (LBA)
/dev/loop0p2      210944 4929535 4718592  2,3G 83 Linux
/dev/loop0p3        2048    6143    4096    2M 2d unknown

As you can see, partition p3 have ID 2d, instead of a2.
I set partition ID to A2 manually (command t) and board start to boot normally with this image.
How to edit recipe to get image with correct partition ID?

**Comment by dwesterg** [comment]
Thanks, I will look into this.  Not sure if the sdcard creation script was changed.  Can you tell me what OS you built this on just in case it is os related?

--dalon

**Comment by grebenkoff** [comment]
Hi, I built on Ubuntu 16.04 running on Acer Aspire V-571g
--
Отправлено из мобильной Почты Mail.Ru
среда, 25 октября 2017г., 21:41 +03:00 от Dalon Westergreen <notifications@github.com>:

**Comment by liqiu** [comment]
try to make /bin/sh point to bash instead of dash:
sudo dpkg-reconfigure dash

or replace echo with /bin/echo in sdcard_image-socfpga.bbclass

The problem here is that some echo can't recognize -e. That is why you got 2d ('-').

**Comment by grebenkoff** [comment]
thanks, I'll try this solution when back to SoC task

**Comment by dwesterg** [comment]
Any reason you don't just move to using wic?

**Comment by grebenkoff** [comment]
What is wic ?

**Comment by dwesterg** [comment]
In the newer meta-altera layer, wic is used to create the SDCard image.  It should be the default when using sumo or angstrom 2018.06

**Comment by grebenkoff** [comment]
Thanks, it's usefull info.....

**Comment by dwesterg** [comment]
Let me know if you have any trouble.
